services:
  threagile:
    image: threagile/threagile:latest
    platform: linux/amd64
    volumes:
      - ./docs/threat-model:/app/work
    command:
      - -verbose
      - -model
      - /app/work/threagile.yml
      - -output
      - /app/work/report
