apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transacciones-api
resources:
  - namespace.yml
  - configmap.yml
  - service.yml
  - deployment.yml
  - hpa.yml
  - ingress.yml
  - pdp.yml
  - migration-job.yml
images:
  - name: 388839923332.dkr.ecr.us-east-1.amazonaws.com/transacciones-api
    newTag: 04a0a4289e68dd44e7a52fbfaada558d27bfbd16
