apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transacciones-api
resources:
  - namespace.yml
  - configmap.yml
  - service.yml
  - deployment.yml
  - hpa.yml
  - ingress.yml
  - pdp.yml
  - migration-job.yml
images:
  - name: 388839923332.dkr.ecr.us-east-1.amazonaws.com/transacciones-api
    newTag: 0aa9d2306c89af0f47ea2f400e2a4aa27a46edf2
