kubectl create secret generic transacciones-api-secret \
  --namespace transacciones-api \
  --from-literal=DB_HOST=<tu-endpoint-rds.rds.amazonaws.com> \
  --from-literal=DB_PORT=5432 \
  --from-literal=DB_USERNAME=<usuario> \
  --from-literal=DB_PASSWORD=<password> \
  --from-literal=DB_NAME=<nombre-db> \
  --from-literal=API_KEY=<api-key> \
  --from-literal=PROVIDER_API_KEY=<provider-key>
